server:
  port: 8889
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    url: jdbc:h2:file:./.h2/zkMonitor;AUTO_SERVER=TRUE
    schema: classpath:db/schema.sql
    password: 123456
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false

mybatis-plus:
  mapper-locations: classpath:mapper/**.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
